# Generated by Django 5.2.4 on 2025-07-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("category", models.CharField(max_length=100)),
                ("item", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                ("quantity_unit", models.CharField(max_length=50)),
                ("price_inr", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=10)),
                ("image_url", models.URLField()),
                ("stock_quantity", models.IntegerField()),
            ],
        ),
    ]
